version: "3.8"
services:
  backend:
    build: ./server
    env_file:
      - .env
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
    depends_on:
      - mongo
  frontend:
    build: ./client
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/app
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
