services:
  client:
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - server
  server:
    hostname: server
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - mongo
  mongo:
    hostname: db
    image: mongo
    expose:
      - "27017"
  caddy:
    image: caddy
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
networks:
  default:
    name: caddy_net
    external: false